"""Generate FINANCEBENCH_ORACLE_SCOPING.md from the ingested + proposed data.

Reproducible: every number in the report comes from this script. No model
calls; no PDF retrieval.
"""

from __future__ import annotations

import json
import re
import statistics as st
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
EX = HERE / "financebench_oracle_examples.jsonl"
CAND = HERE / "financebench_schema_candidates.jsonl"
OUT = HERE / "FINANCEBENCH_ORACLE_SCOPING.md"

DECLINE = re.compile(
    r"(there are none|not measured|cannot|can't|insufficient|unable to determine|"
    r"no information|not provided|not disclosed)", re.I)

ex = {json.loads(l)["financebench_id"]: json.loads(l)
      for l in EX.read_text(encoding="utf-8").splitlines() if l.strip()}
cand = [json.loads(l) for l in CAND.read_text(encoding="utf-8").splitlines() if l.strip()]

n = len(cand)
L = ["# FinanceBench-150 oracle-evidence extension — scoping report\n",
     "Phase-1 scope: **oracle evidence only**. Uses FinanceBench's own "
     "human-annotated `evidence_text` / `evidence_text_full_page`. No RAG, "
     "no PDF retrieval, no model calls. Generated by "
     "`build_financebench_scoping_report.py`.\n"]

# ── 1. load + evidence coverage ─────────────────────────────────────────
n_txt = sum(1 for r in ex.values() if r["evidence_text_joined"])
n_full = sum(1 for r in ex.values() if r["evidence_full_page_joined"])
tl = [len(r["evidence_text_joined"]) for r in ex.values()]
fl = [len(r["evidence_full_page_joined"]) for r in ex.values()]
L.append("## 1. Examples loaded and evidence coverage\n")
L.append(f"- examples loaded: **{len(ex)}**")
L.append(f"- with annotated `evidence_text`: **{n_txt}/{len(ex)}** (100%)")
L.append(f"- with `evidence_text_full_page`: **{n_full}/{len(ex)}** (100%)")
L.append(f"- evidence objects per question: "
         f"{dict(Counter(r['n_evidence'] for r in ex.values()))}")
L.append(f"- `evidence_text` length (chars): median {int(st.median(tl))}, "
         f"p90 {int(sorted(tl)[int(.9*len(tl))-1])}, max {max(tl)}")
L.append(f"- `evidence_text_full_page` length (chars): median {int(st.median(fl))}, "
         f"p90 {int(sorted(fl)[int(.9*len(fl))-1])}, max {max(fl)}")
L.append("\n**Every question ships with gold evidence**, so an oracle-evidence "
         "run needs no retrieval at all. Median evidence fits comfortably in "
         "the existing 4k-token agent context; the p90 full-page variant "
         "(~5.3k chars ≈ 1.3k tokens) also fits. Use `evidence_text` as the "
         "primary pack and `evidence_text_full_page` as a 'wider context' "
         "robustness arm.")

# ── 2. distributions ────────────────────────────────────────────────────
L.append("\n## 2. Question-type and reasoning distributions\n")
L.append("```\nquestion_type\n" + "\n".join(
    f"  {k}: {v}" for k, v in Counter(r["question_type"] for r in ex.values()).most_common()) + "\n```")
L.append("```\nquestion_reasoning\n" + "\n".join(
    f"  {str(k)}: {v}" for k, v in Counter(
        r["question_reasoning"] for r in ex.values()).most_common()) + "\n```")
L.append("(`question_reasoning` is null for the 50 metrics-generated items.)")

# ── 3. proposed answer types ────────────────────────────────────────────
at = Counter(r["proposed_answer_type"] for r in cand)
conf = Counter(r["schema_confidence"] for r in cand)
L.append("\n## 3. Proposed answer types (CANDIDATES — none finalized)\n")
L.append("```\n" + "\n".join(f"  {k}: {v}" for k, v in at.most_common()) + "\n```")
L.append("```\nschema_confidence: " + str(dict(conf)) + "\n```")
L.append("\n```\nanswer_type x confidence\n" + "\n".join(
    f"  {a:26s} {c:7s} {v}" for (a, c), v in sorted(
        Counter((r["proposed_answer_type"], r["schema_confidence"])
                for r in cand).items())) + "\n```")

# ── 4. clean vs special-scoring vs noncommitted ─────────────────────────
yn = [r for r in cand if r["proposed_answer_type"] == "yes_no"]
num = [r for r in cand if r["proposed_answer_type"] == "numeric"]
low = [r for r in cand if r["schema_confidence"] == "low"]
genuine = [r for r in cand if DECLINE.search(r["gold_answer"])]
prop_nc = [r for r in cand if r["gold_commitment"] == "noncommitted"]
gen_ids = {r["financebench_id"] for r in genuine}
L.append("\n## 4. Clean finite-label vs special-scoring vs non-committed\n")
L.append(f"- **clean finite-label now:** yes_no **{len(yn)}** "
         f"({sum(1 for r in yn if r['schema_confidence']=='high')} high-confidence). "
         "These map onto the existing framework immediately.")
L.append(f"- **numeric needing special scoring: {len(num)}** — the gold is a "
         "computed/extracted number. A 3-label space "
         "(correct/wrong/noncommit) is only meaningful if we score the "
         "model's *numeric value* against gold with a tolerance and then "
         "derive the label. Treat as `numeric_freeform` + derived label, "
         "never as a string-matched category.")
L.append(f"- **low-confidence proposals needing rework: {len(low)}** "
         "(claim_verification 28, comparison_direction 10, "
         "company_or_entity_choice 3, open_explanation 5).")
L.append(f"- **proposed non-committed golds: {len(prop_nc)}**, but only "
         f"**{len(gen_ids & {r['financebench_id'] for r in prop_nc})}** of those "
         "are genuine; the rest are artifacts of my fallback rules "
         "(`flat_or_mixed` default, `schema_uncertain` for long prose).")
L.append(f"- **golds containing a genuine decline/none phrase: "
         f"{len(genuine)}/{n} (~{100*len(genuine)/n:.0f}%)**:")
for r in genuine:
    L.append(f"  - `{r['financebench_id']}` — {r['gold_answer'][:90]}")

L.append("\n### ⚠ The single most important scoping finding\n")
L.append(f"FinanceBench golds are **overwhelmingly committed**: only ~"
         f"{len(genuine)}/{n} ({100*len(genuine)/n:.0f}%) decline to answer, "
         "versus **22/139 (15.8%)** non-committal golds in FinTradeBench. "
         "Consequences for the hedge-collision framework:\n")
L.append("1. The **'correct non-commitment' cell is nearly empty** — we cannot "
         "estimate how often hedging is *right*, which was a key FinTradeBench "
         "result (hedging correct ~79% when the gold hedges).")
L.append("2. `p_noncommit`'s AUROC would be **almost purely mechanical** here "
         "(nearly every hedge collides with a committed gold), so the "
         "committed-gold-vs-non-committed-gold *contrast* that made the "
         "FinTradeBench decomposition informative largely disappears.")
L.append("3. What FinanceBench **can** test cleanly: the **hedge-collision "
         "rate itself**, the **wrong-direction commitment rate**, and the "
         "**AU-reduction / EU-flow behaviour** under debate — i.e. three of "
         "the four headline findings, on a genuinely independent benchmark.")
L.append("4. Bonus natural experiment: the yes/no answer space here is "
         "`[yes, no, insufficient_data]` with **no soft hedge label** "
         "(`mixed`/`conditional` do not exist). That is structurally the "
         "'directional_menu' arm of our hedge-attractor probe — it directly "
         "tests the earlier finding that removing soft hedges makes models "
         "migrate to `insufficient_data` rather than commit.")

# ── 5. easiest / hardest ────────────────────────────────────────────────
def ev_len(r):
    return len(ex[r["financebench_id"]]["evidence_text_joined"])


easy = sorted([r for r in cand
               if r["proposed_answer_type"] == "yes_no"
               and r["schema_confidence"] == "high"],
              key=lambda r: (ev_len(r), len(r["gold_answer"])))[:20]
hard_pool = [r for r in cand if r["schema_confidence"] == "low"]
hard = sorted(hard_pool,
              key=lambda r: (r["proposed_answer_type"] != "open_explanation",
                             -len(r["gold_answer"])))[:20]

L.append("\n## 5. Top 20 easiest to adapt (Phase-1 core)\n")
L.append("| # | financebench_id | type | gold | evid chars | question |")
L.append("|---|---|---|---|---|---|")
for i, r in enumerate(easy, 1):
    L.append(f"| {i} | `{r['financebench_id']}` | {r['proposed_answer_type']} | "
             f"{r['proposed_gold_label']} | {ev_len(r)} | "
             f"{r['question'][:80]} |")

L.append("\n## 6. Top 20 hardest / exclude from Phase 1\n")
L.append("| # | financebench_id | proposed type | why hard |")
L.append("|---|---|---|---|")
for i, r in enumerate(hard, 1):
    why = (r["schema_notes"] or "low-confidence reduction")[:95]
    L.append(f"| {i} | `{r['financebench_id']}` | {r['proposed_answer_type']} | {why} |")

# ── 6. suitability verdict ──────────────────────────────────────────────
L.append("\n## 7. Is FinanceBench-150 suitable for the hedge-collision framework?\n")
L.append("**Partially — as a targeted generalization test, not a like-for-like "
         "replication.**\n")
L.append("Suitable because: (a) 100% oracle-evidence coverage means the "
         "'reasoning conditional on gold evidence' design transfers exactly; "
         "(b) it is a genuinely independent benchmark (different companies, "
         "documents, annotators, question construction); (c) the yes/no subset "
         f"({len(yn)} items) is immediately schema-compatible; (d) it can test "
         "hedge-collision rate, wrong-direction rate, and AU/EU debate dynamics.")
L.append("\nNot suitable for: (a) the **non-committed-gold analyses** "
         "(correct-noncommitment rate, the AUROC inversion on non-committed "
         "golds) — too few non-committal golds; (b) **lane-structured claims** "
         "— FinanceBench has no F/T/FT analogue, so the model×lane regime map "
         "cannot be replicated; (c) **numeric items** without a new "
         "tolerance-based scorer.")
L.append(f"\nHeadline caveat to state in any writeup: with only ~"
         f"{100*len(genuine)/n:.0f}% non-committal golds, a high hedge-collision "
         "share on FinanceBench is **partly guaranteed by the benchmark's "
         "construction** and must not be reported as an independent "
         "confirmation of the FinTradeBench rate without that caveat.")

OUT.write_text("\n".join(L), encoding="utf-8")
print(f"wrote {OUT.name}")
print(f"easiest: {len(easy)}; hardest: {len(hard)}; genuine declines: {len(genuine)}")


